# This Makefile was generated by Mesa v2.1
# Generation Date: 1721662494
# DO NOT EDIT THIS FILE AS IT WILL BE RE-GENERATED

################### VARIABLES ###################

CTime.UnixTimestamp := 1721662494
Global.Includes :=  [Libraries\Test\Includes]
CTime.Formatted := Mon\ Jul\ 22\ 11:34:54\ 2024
CXX := /usr/bin/g++
I_CPPFLAGS := -DMESA_BUILD
BIN_DIR := bin
OBJ_DIR := $(BIN_DIR)/objs
Mesa_Scriptlets_INCDIRS := 
Mesa_Scriptlets_CPPFLAGS :=  
Mesa_Utils_INCDIRS := 
Mesa_Utils_CPPFLAGS :=  
Mesa_Base_INCDIRS := $(wildcard ./*.h) $(wildcard ./*.hpp)
Mesa_Base_CPPFLAGS := -DBUILD_UNIX=1721662494 -DBUILD_DATE=Mon\ Jul\ 22\ 11:34:54\ 2024 -I.  

################### PROJECTS ###################

all: Mesa_Scriptlets Mesa_Utils Mesa_Base 

clean:
	@echo [RM] Purging contents of $(BIN_DIR)
	@rm -rf $(BIN_DIR)/*

Prep:
	@echo [MKDIR] Creating $(OBJ_DIR)
	@mkdir -p $(OBJ_DIR)
	@mkdir -p $(OBJ_DIR)/Mesa_Scriptlets	@mkdir -p $(OBJ_DIR)/Mesa_Utils	@mkdir -p $(OBJ_DIR)/Mesa_Base
$(OBJ_DIR)/Mesa_Scriptlets/ProjectScriptlets.cpp.o: ProjectScriptlets.cpp $(Mesa_Scriptlets_INCDIRS)
	@echo [CXX] ProjectScriptlets.cpp
	@$(CXX) $(CPPFLAGS) $(Mesa_Scriptlets_CPPFLAGS) $(I_CPPFLAGS) -c ProjectScriptlets.cpp -o $(OBJ_DIR)/Mesa_Scriptlets/ProjectScriptlets.cpp.o

$(OBJ_DIR)/Mesa_Scriptlets/StdScriptlets.cpp.o: StdScriptlets.cpp $(Mesa_Scriptlets_INCDIRS)
	@echo [CXX] StdScriptlets.cpp
	@$(CXX) $(CPPFLAGS) $(Mesa_Scriptlets_CPPFLAGS) $(I_CPPFLAGS) -c StdScriptlets.cpp -o $(OBJ_DIR)/Mesa_Scriptlets/StdScriptlets.cpp.o

$(OBJ_DIR)/Mesa_Scriptlets/WorkspaceScriptlets.cpp.o: WorkspaceScriptlets.cpp $(Mesa_Scriptlets_INCDIRS)
	@echo [CXX] WorkspaceScriptlets.cpp
	@$(CXX) $(CPPFLAGS) $(Mesa_Scriptlets_CPPFLAGS) $(I_CPPFLAGS) -c WorkspaceScriptlets.cpp -o $(OBJ_DIR)/Mesa_Scriptlets/WorkspaceScriptlets.cpp.o

Mesa_Scriptlets: Prep $(OBJ_DIR)/Mesa_Scriptlets/ProjectScriptlets.cpp.o $(OBJ_DIR)/Mesa_Scriptlets/StdScriptlets.cpp.o $(OBJ_DIR)/Mesa_Scriptlets/WorkspaceScriptlets.cpp.o 
	@echo [EXE] Linking Mesa Scriptlets \> $(BIN_DIR)/MesaScriptlets
	@$(CXX) -o $(BIN_DIR)/MesaScriptlets $(OBJ_DIR)/Mesa_Scriptlets/ProjectScriptlets.cpp.o $(OBJ_DIR)/Mesa_Scriptlets/StdScriptlets.cpp.o $(OBJ_DIR)/Mesa_Scriptlets/WorkspaceScriptlets.cpp.o 

$(OBJ_DIR)/Mesa_Utils/MesaUtils.cpp.o: MesaUtils.cpp $(Mesa_Utils_INCDIRS)
	@echo [CXX] MesaUtils.cpp
	@$(CXX) $(CPPFLAGS) $(Mesa_Utils_CPPFLAGS) $(I_CPPFLAGS) -c MesaUtils.cpp -o $(OBJ_DIR)/Mesa_Utils/MesaUtils.cpp.o

Mesa_Utils: Prep $(OBJ_DIR)/Mesa_Utils/MesaUtils.cpp.o 
	@echo [EXE] Linking Mesa Utils \> $(BIN_DIR)/MesaUtils
	@$(CXX) -o $(BIN_DIR)/MesaUtils $(OBJ_DIR)/Mesa_Utils/MesaUtils.cpp.o 

$(OBJ_DIR)/Mesa_Base/Mesa.cpp.o: Mesa.cpp $(Mesa_Base_INCDIRS)
	@echo [CXX] Mesa.cpp
	@$(CXX) $(CPPFLAGS) $(Mesa_Base_CPPFLAGS) $(I_CPPFLAGS) -c Mesa.cpp -o $(OBJ_DIR)/Mesa_Base/Mesa.cpp.o

$(OBJ_DIR)/Mesa_Base/MesaParser.cpp.o: MesaParser.cpp $(Mesa_Base_INCDIRS)
	@echo [CXX] MesaParser.cpp
	@$(CXX) $(CPPFLAGS) $(Mesa_Base_CPPFLAGS) $(I_CPPFLAGS) -c MesaParser.cpp -o $(OBJ_DIR)/Mesa_Base/MesaParser.cpp.o

$(OBJ_DIR)/Mesa_Base/MesaGenerator.cpp.o: MesaGenerator.cpp $(Mesa_Base_INCDIRS)
	@echo [CXX] MesaGenerator.cpp
	@$(CXX) $(CPPFLAGS) $(Mesa_Base_CPPFLAGS) $(I_CPPFLAGS) -c MesaGenerator.cpp -o $(OBJ_DIR)/Mesa_Base/MesaGenerator.cpp.o

$(OBJ_DIR)/Mesa_Base/MesaProcessor.cpp.o: MesaProcessor.cpp $(Mesa_Base_INCDIRS)
	@echo [CXX] MesaProcessor.cpp
	@$(CXX) $(CPPFLAGS) $(Mesa_Base_CPPFLAGS) $(I_CPPFLAGS) -c MesaProcessor.cpp -o $(OBJ_DIR)/Mesa_Base/MesaProcessor.cpp.o

$(OBJ_DIR)/Mesa_Base/MesaUtils.cpp.o: MesaUtils.cpp $(Mesa_Base_INCDIRS)
	@echo [CXX] MesaUtils.cpp
	@$(CXX) $(CPPFLAGS) $(Mesa_Base_CPPFLAGS) $(I_CPPFLAGS) -c MesaUtils.cpp -o $(OBJ_DIR)/Mesa_Base/MesaUtils.cpp.o

Mesa_Base: Prep $(OBJ_DIR)/Mesa_Base/Mesa.cpp.o $(OBJ_DIR)/Mesa_Base/MesaParser.cpp.o $(OBJ_DIR)/Mesa_Base/MesaGenerator.cpp.o $(OBJ_DIR)/Mesa_Base/MesaProcessor.cpp.o $(OBJ_DIR)/Mesa_Base/MesaUtils.cpp.o 
	@echo [EXE] Linking Mesa Base \> $(BIN_DIR)/Mesa
	@$(CXX) -o $(BIN_DIR)/Mesa $(OBJ_DIR)/Mesa_Base/Mesa.cpp.o $(OBJ_DIR)/Mesa_Base/MesaParser.cpp.o $(OBJ_DIR)/Mesa_Base/MesaGenerator.cpp.o $(OBJ_DIR)/Mesa_Base/MesaProcessor.cpp.o $(OBJ_DIR)/Mesa_Base/MesaUtils.cpp.o 

.PHONY: clean
